# Default values for flexplorer
replicaCount: 1

image:
  repository: vitexsoftware/flexplorer
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: flexplorer.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: flexplorer-tls
  #    hosts:
  #      - flexplorer.example.com

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Flexplorer specific configuration
flexplorer:
  # ABRA Flexi connection settings
  flexibeeUrl: "https://demo.flexibee.eu"
  flexibeeLogin: "winstrom"
  flexibeePassword: "winstrom"
  flexibeeCompany: "demo"
  backupDirectory: "/var/tmp"

# Persistence for backups (optional)
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  # existingClaim: ""
