<?php

namespace Flexplorer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:33:39.
 */
class DataSourceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DataSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DataSource;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Flexplorer\DataSource::getEvidence
     * @todo   Implement testGetEvidence().
     */
    public function testGetEvidence()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::setOrder
     * @todo   Implement testSetOrder().
     */
    public function testSetOrder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::setBackUrl
     * @todo   Implement testSetBackUrl().
     */
    public function testSetBackUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::ajaxify
     * @todo   Implement testAjaxify().
     */
    public function testAjaxify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getTotal
     * @todo   Implement testGetTotal().
     */
    public function testGetTotal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getListing
     * @todo   Implement testGetListing().
     */
    public function testGetListing()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getJson
     * @todo   Implement testGetJson().
     */
    public function testGetJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getCsv
     * @todo   Implement testGetCsv().
     */
    public function testGetCsv()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getPdf
     * @todo   Implement testGetPdf().
     */
    public function testGetPdf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::output
     * @todo   Implement testOutput().
     */
    public function testOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::pdfInit
     * @todo   Implement testPdfInit().
     */
    public function testPdfInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getPDFFromArray
     * @todo   Implement testGetPDFFromArray().
     */
    public function testGetPDFFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getPDFFile
     * @todo   Implement testGetPDFFile().
     */
    public function testGetPDFFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::controlColumns
     * @todo   Implement testControlColumns().
     */
    public function testControlColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::controlDeleteColumns
     * @todo   Implement testControlDeleteColumns().
     */
    public function testControlDeleteColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::controlAddColumns
     * @todo   Implement testControlAddColumns().
     */
    public function testControlAddColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::controlEditColumns
     * @todo   Implement testControlEditColumns().
     */
    public function testControlEditColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\DataSource::getWhere
     * @todo   Implement testGetWhere().
     */
    public function testGetWhere()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
