<?php

declare(strict_types=1);

/**
 * This file is part of the Flexplorer package
 *
 * github.com/VitexSoftware/Flexplorer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Flexplorer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:33:39.
 */
class DataSourceTest extends \PHPUnit\Framework\TestCase
{
    protected DataSource $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new DataSource();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Flexplorer\DataSource::getEvidence
     *
     * @todo   Implement testGetEvidence().
     */
    public function testGetEvidence(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::setOrder
     *
     * @todo   Implement testSetOrder().
     */
    public function testSetOrder(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::setBackUrl
     *
     * @todo   Implement testSetBackUrl().
     */
    public function testSetBackUrl(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::ajaxify
     *
     * @todo   Implement testAjaxify().
     */
    public function testAjaxify(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getTotal
     *
     * @todo   Implement testGetTotal().
     */
    public function testGetTotal(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getListing
     *
     * @todo   Implement testGetListing().
     */
    public function testGetListing(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getJson
     *
     * @todo   Implement testGetJson().
     */
    public function testGetJson(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getCsv
     *
     * @todo   Implement testGetCsv().
     */
    public function testGetCsv(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getPdf
     *
     * @todo   Implement testGetPdf().
     */
    public function testGetPdf(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::output
     *
     * @todo   Implement testOutput().
     */
    public function testOutput(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::pdfInit
     *
     * @todo   Implement testPdfInit().
     */
    public function testPdfInit(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getPDFFromArray
     *
     * @todo   Implement testGetPDFFromArray().
     */
    public function testGetPDFFromArray(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getPDFFile
     *
     * @todo   Implement testGetPDFFile().
     */
    public function testGetPDFFile(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::controlColumns
     *
     * @todo   Implement testControlColumns().
     */
    public function testControlColumns(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::controlDeleteColumns
     *
     * @todo   Implement testControlDeleteColumns().
     */
    public function testControlDeleteColumns(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::controlAddColumns
     *
     * @todo   Implement testControlAddColumns().
     */
    public function testControlAddColumns(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::controlEditColumns
     *
     * @todo   Implement testControlEditColumns().
     */
    public function testControlEditColumns(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\DataSource::getWhere
     *
     * @todo   Implement testGetWhere().
     */
    public function testGetWhere(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }
}
