<?php

namespace Flexplorer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:33:40.
 */
class FlexplorerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Flexplorer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Flexplorer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Flexplorer\Flexplorer::htmlizeData
     * @todo   Implement testHtmlizeData().
     */
    public function testHtmlizeData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\Flexplorer::htmlizeRow
     * @todo   Implement testHtmlizeRow().
     */
    public function testHtmlizeRow() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\Flexplorer::searchString
     * @todo   Implement testSearchString().
     */
    public function testSearchString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\Flexplorer::takeData
     * @todo   Implement testTakeData().
     */
    public function testTakeData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\Flexplorer::contains
     * @todo   Implement testContains().
     */
    public function testContains() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
