<?php

declare(strict_types=1);

/**
 * This file is part of the Flexplorer package
 *
 * github.com/VitexSoftware/Flexplorer
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Flexplorer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:33:40.
 */
class FlexplorerTest extends \PHPUnit\Framework\TestCase
{
    protected Flexplorer $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Flexplorer();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * @covers \Flexplorer\Flexplorer::htmlizeData
     *
     * @todo   Implement testHtmlizeData().
     */
    public function testHtmlizeData(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\Flexplorer::htmlizeRow
     *
     * @todo   Implement testHtmlizeRow().
     */
    public function testHtmlizeRow(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\Flexplorer::searchString
     *
     * @todo   Implement testSearchString().
     */
    public function testSearchString(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\Flexplorer::takeData
     *
     * @todo   Implement testTakeData().
     */
    public function testTakeData(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }

    /**
     * @covers \Flexplorer\Flexplorer::contains
     *
     * @todo   Implement testContains().
     */
    public function testContains(): void
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.',
        );
    }
}
