<?php

namespace Flexplorer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-12 at 15:33:41.
 */
class SearcherTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Searcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Searcher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Flexplorer\Searcher::registerEvidence
     * @todo   Implement testRegisterEvidence().
     */
    public function testRegisterEvidence()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Flexplorer\Searcher::searchAll
     * @todo   Implement testSearchAll().
     */
    public function testSearchAll()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
