README.md			usr/share/flexplorer/
src/*.php                       usr/share/flexplorer/
src/*.ico                       usr/share/flexplorer/
src/css/*.css                   usr/share/flexplorer/css/
src/css/images/*                usr/share/flexplorer/css/images/
src/js/*.js                     usr/share/flexplorer/js/
src/images/*                    usr/share/flexplorer/images/
src/includes/*.php		usr/share/flexplorer/includes/
src/Flexplorer/*.php		usr/lib/flexplorer/classes/
src/Flexplorer/ui/*.php		usr/lib/flexplorer/classes/ui/
src/Flexplorer/xml/*.php	usr/lib/flexplorer/classes/xml/
src/download/*                  usr/share/flexplorer/download/
debian/flexplorer.conf		etc/apache2/conf-available/
debian/flexplorer.service	etc/avahi/services/
debian/autoload.php		var/lib/flexplorer/
debian/flexplorer.desktop	etc/flexplorer/

i18n/cs_CZ/LC_MESSAGES/*.mo     usr/share/locale/cs_CZ/LC_MESSAGES
i18n/en_US/LC_MESSAGES/*.mo     usr/share/locale/en_US/LC_MESSAGES

flexplorer.svg                  usr/share/icons/hicolor/scalable/apps/
debian/io.github.vitexsoftware.flexplorer.metainfo.xml usr/share/metainfo/
