#!/bin/sh
# postinst script for flexplorer

set -e

desktop_install() {
	if [ -f /usr/bin/xdg-desktop-menu ]; then
	    xdg-desktop-menu install --novendor /usr/share/applications/flexplorer.desktop > /dev/null || true
        else
            if [ -d /usr/share/applications/ -a ! -e /usr/share/applications/flexplorer.desktop -a ! -L /usr/share/applications/flexplorer.desktop ] ; then
               	ln -s /etc/flexplorer/flexplorer.desktop /usr/share/applications/
            fi
	fi
}


apache_install() {
	COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		apache2_invoke enconf flexplorer
	elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
		[ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/flexplorer.conf ] && ln -s ../conf-available/flexplorer.conf /etc/apache2/conf.d/flexplorer.conf
	fi
}


    if [ "$1" = "configure" ]; then

    . /usr/share/debconf/confmodule

    debian-composer flexplorer

    db_get flexplorer/FLEXIBEE_URL
    sed -i "/DEFAULT_FLEXIBEE_URL/c\define('DEFAULT_FLEXIBEE_URL', '${RET}');" /usr/share/flexplorer/includes/config.php

    db_get flexplorer/FLEXIBEE_LOGIN
    sed -i "/DEFAULT_FLEXIBEE_LOGIN/c\define('DEFAULT_FLEXIBEE_LOGIN', '${RET}');" /usr/share/flexplorer/includes/config.php

    db_get flexplorer/FLEXIBEE_PASSWORD
    sed -i "/DEFAULT_FLEXIBEE_PASSWORD/c\define('DEFAULT_FLEXIBEE_PASSWORD', '${RET}');" /usr/share/flexplorer/includes/config.php

    db_get flexplorer/FLEXIBEE_COMPANY
    sed -i "/DEFAULT_FLEXIBEE_COMPANY/c\define('DEFAULT_FLEXIBEE_COMPANY', '${RET}');" /usr/share/flexplorer/includes/config.php

    db_get flexplorer/BACKUP_DIRECTORY
    sed -i "/DEFAULT_BACKUP_DIRECTORY/c\define('DEFAULT_BACKUP_DIRECTORY', '${RET}');" /usr/share/flexplorer/includes/config.php

            apache_install $1
                    # Reload webserver in any case, configuration might have changed
                    # Redirection of 3 is needed because Debconf uses it and it might 
                    # be inherited by webserver. See bug #446324.
            if [ -f /etc/init.d/apache2 ] ; then
                if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d apache2 reload 3>/dev/null || true
                else
                    /etc/init.d/apache2 reload 3>/dev/null || true
                fi
            fi

            if [ -f /etc/init.d/avahi ] ; then
                if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d avahi reload 3>/dev/null || true
                else
                    /etc/init.d/avahi reload 3>/dev/null || true
                fi
            fi

	    desktop_install
    fi


#DEBHELPER#

exit 0
